name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ladspa-sdk
      run: |
        sudo apt update
        sudo apt install ladspa-sdk
    - name: make
      run: make
